---
engine_version: 0.4.20
file_version: 2023-07-23 16:15:32.351650000 +03:30
resources:
- name: user
  preferences:
    columns:
    - access_type: hidden
      name: password_digest
  updated_at: 2023-07-23 16:15:32.351650000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2023-07-22 14:34:11.618342000 +00:00
- key: resources.account_detail.columns.order
  value:
  - id
  - address1
  - address2
  - postal_code
  - user_id
  updated_at: 2023-07-22 14:35:15.924531000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2023-07-22 14:34:11.633033000 +00:00
